events {}

http {

  upstream apps {
    server app1:80;
    server app2:80;
  }

  server {
    listen 80;

    # Página principal (load balancer)
    location / {
      proxy_pass http://apps;
    }

    # Status para o exporter do Prometheus
    location /status {
      stub_status;
      allow all;
    }
  }
}